### ISSUE TITLE
Cannot find dataset download address

### ISSUE THREAD

**Issue by I-Good-Vegetable** [DFKI-NLP/MultiTACRED#2]
Hi,

I tried to use MultiTACREFD from huggingface, however, I got the following issue:
```
To use MultiTACRED you have to download it manually. It is available via the LDC at https://catalog.ldc.upenn.edu/LDC2023_TODOPlease extract all files in one folder and load the a language with: `datasets.load_dataset('DFKI-SLT/multitacred', name='variant-language', data_dir='path/to/folder/folder_name')`.
```
I tried to download from https://catalog.ldc.upenn.edu/LDC2023_TODO, but the page does not exist.

I'm wondering whether the download link is expired or changed, and where to get this great dataset

Many thanks

**Comment by leonhardhennig** [comment]
Hi,
unfortunately, LDC still hasn't released the data. I submitted it in June last year, they approved in November, and told me they would schedule it for 2024. I'll update the catalog link as soon as they release the dataset.

**Comment by I-Good-Vegetable** [comment]
Thanks for letting me know! Looking forward to it

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Leonhard Hennig ***@***.***>
发送时间: Friday, July 5, 2024 3:35:30 AM
收件人: DFKI-NLP/MultiTACRED ***@***.***>
抄送: Jason ***@***.***>; Author ***@***.***>
主题: Re: [DFKI-NLP/MultiTACRED] Cannot find dataset download address (Issue #2)


Hi,
unfortunately, LDC still hasn't released the data. I submitted it in June last year, they approved in November, and told me they would schedule it for 2024. I'll update the catalog link as soon as they release the dataset.

―

**Comment by leonhardhennig** [comment]
Hi,
the dataset has finally been released: [https://catalog.ldc.upenn.edu/LDC2024T09](https://catalog.ldc.upenn.edu/LDC2024T09)

**Comment by I-Good-Vegetable** [comment]
Great News! Thanks for letting me know

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Leonhard Hennig ***@***.***>
发送时间: Thursday, October 17, 2024 5:27:01 AM
收件人: DFKI-NLP/MultiTACRED ***@***.***>
抄送: Jason ***@***.***>; Author ***@***.***>
主题: Re: [DFKI-NLP/MultiTACRED] Cannot find dataset download address (Issue #2)


Hi,
the dataset has finally been released: https://catalog.ldc.upenn.edu/LDC2024T09

―
